var intro = '';
intro  = '<div id="intro1" style="padding:60px 10px 10px 10px; display:block; height:590px;">';
intro += '  <img style="float:left;" src="_media/intro_board.png">';
intro += '  <div style="float:right;width:360px;">';
intro += '    <div>Utactica is a hot seat game for two players. The aim of the game is to occupy your enemy\'s home base, thus taking control of Utactica and its resources.</div>';
intro += '    <div style="padding-top:10px;">The Mecritians start from their home base at the top of the map, while the Riveckian\'s home base is at the bottom of the map.</div>';
intro += '  </div>';
intro += '  <div style="float:left;clear:both;width:360px;">';
intro += '    <div style="padding-top:10px;">Two types of resources can be collected in the game.</div>';
intro += '    <div style="padding-top:10px;"><b>Food resources</b> can be spent on buidling new units, and <b>Science resources</b> can be spent on upgrading the capabilities of your units. Resources are randomly distributed across the map.</div>';
intro += '    <div style="padding-top:10px;">The number on the resource tiles shows the number of resources that will be colleted if a worker is placed in the tile each turn.</div>';
intro += '  </div>';
intro += '  <img style="float:right;" src="_media/intro_resources.png">';
intro += '  <div style="clear:both;"></div>';
intro += '  <div style="text-align:center;font-size:140%;position:absolute;bottom:0px;width:700px;">';
intro += '    <span onclick="getElementById(\'intro1\').style.display=\'none\';getElementById(\'intro2\').style.display=\'block\';" onmouseover="document.body.style.cursor=\'pointer\';" onmouseout="document.body.style.cursor=\'default\';">Next >></span>';
intro += '  </div>';
intro += '</div>';

intro += '<div id="intro2" style="padding:60px 10px 10px 10px; display:none; height:590px;">';
intro += '  <div>';
intro += '    <img style="float:left;" src="_media/intro_soldiers.png">';
intro += '    <div style="float:right;width:420px;">';
intro += '      <div><b>Soldier units</b> can attack and defend against other units. Damaged soldiers can return to home base to be repaired to full health.</div>';
intro += '      <div style="padding-top:10px;">You can upgrade your soldier\'s skills with collected science resources.</div>';
intro += '      <div style="padding-top:10px;">Surviving multiple battles may lead to a soldier being promoted to an elite unit. Elite units receive battle bonuses.</div>';
intro += '    </div>';
intro += '    <div style="clear:both;"></div>';
intro += '  </div>';
intro += '  <div style="padding-top:20px;">';
intro += '    <img style="float:left;" src="_media/intro_workers.png">';
intro += '    <div style="float:right;width:420px;">';
intro += '      <div><b>Worker units</b> collect resources from resource tiles, and cannot attack or defend. When attacked a worker will emergency teleport back to home base. If there is no free space at the home base the worker will be destroyed.</div>';
intro += '      <div style="padding-top:10px;">Upgrading production increases the amount of resources workers can harvest each turn. Upgrading worker movement allows them to move further each turn (starting from the next turn).</div>';
intro += '    </div>';
intro += '    <div style="clear:both;"></div>';
intro += '  </div>';
intro += '  <p style="clear:both;">Both soldiers and workers can manually teleport back to home base on their turn. This can be useful for repairing damaged soldiers.</p>';
intro += '  <p><b>Battles</b></p>';
intro += '  <p>A group of more than one soldier automatically receives a defensive bonus. Soldiers defending their home base also gain a defensive bonus.</p>';
intro += '  <div style="text-align:center;font-size:140%;position:absolute;bottom:0px;width:700px;">';
intro += '    <span onclick="getElementById(\'intro2\').style.display=\'none\';getElementById(\'intro1\').style.display=\'block\';" onmouseover="document.body.style.cursor=\'pointer\';" onmouseout="document.body.style.cursor=\'default\';"><< Prev</span>';
intro += '    &nbsp; <span onclick="getElementById(\'intro2\').style.display=\'none\';getElementById(\'intro3\').style.display=\'block\';" onmouseover="document.body.style.cursor=\'pointer\';" onmouseout="document.body.style.cursor=\'default\';">Next >></span>';
intro += '  </div>';
intro += '</div>';

intro += '<div id="intro3" style="padding:60px 10px 10px 10px; display:none; height:590px;">';
intro += '  <p style="margin-top:0px;"><b>Controls</b></p>';
intro += '  <p>Drag and drop units to move them. The board will highlight the tiles you can reach on that turn. Units that have already moved will be greyed out.</p>';
intro += '  <p>Click on a unit to select it and click "Teleport" to send it back to home base.</p>';
intro += '  <p>To end your turn and let the other player move click "End turn".</p>';
intro += '  <p><b>Shortcut keys</b></p>';
intro += '  <p>"T" Teleport</p>';
intro += '  <p>"Space" End turn</p>';
intro += '  <p>"H" This introduction</p>';
intro += '  <p>"M" Mute the sound</p>';
intro += '  <div style="text-align:center;font-size:140%;position:absolute;bottom:0px;width:700px;">';
intro += '    <span onclick="getElementById(\'intro3\').style.display=\'none\';getElementById(\'intro2\').style.display=\'block\';" onmouseover="document.body.style.cursor=\'pointer\';" onmouseout="document.body.style.cursor=\'default\';"><< Prev</span>';
intro += '    &nbsp; <span onclick="ui.popup.hidePopup();" onmouseover="document.body.style.cursor=\'pointer\';" onmouseout="document.body.style.cursor=\'default\';">Play Game >></span>';
intro += '  </div>';
intro += '</div>';


var winner = '';
winner  = '<div id="winner" style="padding:60px 10px 10px 10px; height:590px;">';
winner += '  <div style="font-size:150%; padding-top:10px;">You have reigned supreme. Your foe has been driven out and now the burnt out husk of the once great planet of Utactica is yours.</div>';
winner += '  <div style="font-size:150%; padding-top:10px;">In other news, word has just come to hand of a newly discovered world, overflowing with resources, a world that must be claimed at all costs.</div>';
winner += '  <div style="font-size:150%; padding-top:10px;">Good luck in the coming battle.</div>';
winner += '  <div style="text-align:center;padding-top:50px;"> <img src="_media/winner.jpg" /> </div>';
//winner += '  <div style="text-align:center;font-size:140%;position:absolute;bottom:0px;width:700px;">';
//winner += '    <span onclick="getElementById(\'intro3\').style.display=\'none\';getElementById(\'intro2\').style.display=\'block\';" onmouseover="document.body.style.cursor=\'pointer\';" onmouseout="document.body.style.cursor=\'default\';"><< Prev</span>';
//winner += '    &nbsp; <span onclick="var div=document.getElementById(\'popupdiv\'); div.parentNode.removeChild(div); ui.popup=false;" onmouseover="document.body.style.cursor=\'pointer\';" onmouseout="document.body.style.cursor=\'default\';">Play Game >></span>-->';
//winner += '  </div>';
winner += '</div>';